name: Deploy Python API

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      # ============================
      # Leer IP desde Terraform state
      # ============================
      - name: Get EC2 IP from Terraform state
        id: tf_ip
        run: |
          cd iac
          terraform init -input=false
          echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      # ============================
      # Copiar app
      # ============================
      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: |
              app
              Dockerfile
              requirements.txt
          target: "/home/deploy/app"

      # ============================
      # Build & Run
      # ============================
      - name: Build & Run container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app

            docker stop python_api || true
            docker rm python_api || true

            docker build -t python_api .
            docker run -d \
              --name python_api \
              -p 8000:8000 \
              --restart unless-stopped \
              python_api

