name: Deploy Python API

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - name: Get EC2 IP from Terraform state
        run: |
          cd iac
          terraform init -input=false
          echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: |
            app/
            Dockerfile
            requirements.txt
          target: "/home/deploy/app"

      - name: Build & Run container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app

            sudo docker stop python_api || true
            sudo docker rm python_api || true

            sudo docker build -t python_api .
            sudo docker run -d \
              --name python_api \
              -p 8000:8000 \
              --restart unless-stopped \
              python_api

